### ISSUE TITLE
For divided plots, plot title placement is ambiguous. 

### ISSUE THREAD

**Issue by ErnstMelchior** [ICJIA/arrest_explorer#16]
Describe Issue
If I go to year by race by age group, and look at Native Americans, it is not immediately clear whether that title refers to the graph above or below the title.  I can figure it out, but I shouldn't need to

![image](https://user-images.githubusercontent.com/41635929/118006706-1bf83780-b311-11eb-9cca-455a54a47f83.png)

 
![image](https://user-images.githubusercontent.com/41635929/118006788-2fa39e00-b311-11eb-91b5-d713ac85bca0.png)

Location of Text or Control
year by race by age group
Current Text or Control
The heading for the interior data breakdown
Proposed new text/control
Put a dark line below each graph, or a box around each graph, or just more space.

**Comment by miserman** [comment]
bcdceced653c61c4dcd7ef57d1158c7fb46658c4 adds a little more room between panels, and increases the label size.

**Comment by kgruschow** [comment]
the plot title placement is still overall ambiguous to the user. in the screenshot here:

![image](https://user-images.githubusercontent.com/48029452/121377168-c0b56700-c907-11eb-9215-e7b13e9f2b41.png)

1. note that "year" is overlapping the plot at bottom of screen
2. the placement of the various "Crime Type: .." labels is lighter in color and also place in a manner that resembles the placement of the x axis label "year".  Literally it collides currently depending on scrolling.

Potential options that seem to match common practice in social sciences for showing multiple groups graphs:
1. left align the text and place above the graph it is describing
2. place the graph title inside a bounding box with the graph
3. use a line / rule to visually divide the graphs, and space the title sufficiently below the rule so that it is clear that the title is for the graph below the rule/title

**Comment by miserman** [comment]
069620a9fd1f27df5df7dc8e7bb99cfba33ab9ea left-aligns panel titles.

**Comment by kgruschow** [comment]
the left align does not look great but to me at least is no longer ambiguous. closing
