### ISSUE TITLE
Settings such as splits are retained by app/browser even when loading an external URL

### ISSUE THREAD

**Issue by kgruschow** [ICJIA/arrest_explorer#4]
When using the app, if the user has already been using the application, current settings can interfere with loading saved URLs or other links. 

To replicate: 
First use the app to set the following:
![Step 1 for sticky settings](https://user-images.githubusercontent.com/48029452/117354128-9985f880-ae76-11eb-86d7-da4b836bb77e.PNG)

Second: 
load the following, which does not contain the filter, however it will still be filtered:
[https://icjia.illinois.gov/arrestexplorer/?plot_type=bar&value=arrests&split=race&by_year=true&format_category=indices](https://icjia.illinois.gov/arrestexplorer/?plot_type=bar&value=arrests&split=race&by_year=true&format_category=indices)

it's not yet clear to me at what level this sticks, however the application seems to retain the settings, and in some cases adding arguments to a call it will union with existing settings

**Comment by miserman** [comment]
Currently, some settings are saved in the browser's storage. This makes most sense for settings like theme, animation, and sending data, but maybe not for aspects of the data view. Changing which settings are saved would be easy.

Settings entered through the URL will overwrite saved settings, but only those specified, so other saved settings may apply. If we stop saving data-view-related settings, this might not be an issue. Otherwise, we could clear all such setting when settings are entered through the URL.

Relating to #10, there is a reset options button in the options menu, which clears all local storage, and so, returns to the default data view. If we don't save those settings to begin with, a page refresh would have the same "home view" effect. Otherwise, we could add a button to clear only data-view-related settings.

**Comment by kgruschow** [comment]
The "both-and" option you describe, i.e. only store visual aspects like theme/animation in browser memory AND have a "home" button is probably the preferred route.

The intended audience for this would be basically people that google around crime in Illinois, so journalists/legislators/etc, not data researchers/analysts, which is to say even expecting the user to understand that there is a state to reset is optimistic.

**Comment by miserman** [comment]
bcdceced653c61c4dcd7ef57d1158c7fb46658c4 disables saving of data-view-related settings, and adds a setting to turn it back on (if only for testing).
