### ISSUE TITLE
Wording: Use of "Between"/"Within" Confusing

### ISSUE THREAD

**Issue by ErnstMelchior** [ICJIA/arrest_explorer#8]
**Describe Issue**
Any graph heading with selections will use confusing words within or between.  These should always say "by" even if the word "by" occurs three times in the heading.

**Location of Text or Control**
All graphs.
![image](https://user-images.githubusercontent.com/41635929/118011005-29afbc00-b315-11eb-9a25-43b203aaf5a2.png)

**Current Text or Control**
Word between or within

**Proposed new text/control**
by

**Comment by kgruschow** [comment]
In the filter settings it consistently uses "by".

![image](https://user-images.githubusercontent.com/48029452/118306177-a924c300-b4ae-11eb-9210-807fe89ca514.png)
(e.g. by Year by Gender by County)

The specific method used by the application seems to be that the first, middle, and last variables are presented as:
{subject} by {first} within  {middle} between {last}

example:
![image](https://user-images.githubusercontent.com/48029452/118306631-4da70500-b4af-11eb-8723-b10552d5a86c.png)


Alternate proposal 1: instead of "first by second by third", "by first, second, and third"

**Comment by miserman** [comment]
The "by"s in the filter settings are specifically "split by", which is the same for all variables, whereas the "by" in the title is a plotting usage (i.e., y by x). In that sense, adding "by"s or listing variables after "by" would be changing its meaning, which is fine.

My thinking for the other terms was to say "within" when levels are each panels, and "between" when levels are separate lines/bars/points.

I don't know that any scheme is inherently more correct or clear, but I like "by first, second, and third" if only for compactness.

**Comment by kgruschow** [comment]
agreed that there is not really an ideal option, the concern with words like within/between is that they evoke common research comparisons, e.g. between groups/within groups comparisons in a way that does not fit for viewing operational/descriptive .

**Comment by miserman** [comment]
bcdceced653c61c4dcd7ef57d1158c7fb46658c4 changes this to a list scheme.

**Comment by kgruschow** [comment]
I think it is good though year (when included) should always come last

e.g. by year, by gender and year, by race, gender, and year
